# Generated by Django 3.1 on 2020-08-17 01:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamLevels',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dam', models.CharField(max_length=100)),
                ('ThisWeek', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LastWeek', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LastYear', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreationDate', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'DamLevels',
            },
        ),
    ]
